plugins:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - "node_modules/"
  - "server/src/test/"
  - "client/__tests__/"
  - "e2e-tests/"
  - "client/public/"
  - "template/"
