language: node_js
node_js:
 - "stable"

install: npm install

services:
  - postgresql
env:
  - NODE_ENV=test
  - DB_NAME_TEST=more_recipes_test


before_script:
  - psql -c 'create database more_recipes_test;' -U postgres
  - npm run build
  - sequelize db:migrate
  - sequelize db:seed:all

script: npm test

after_success: npm run coverage
