language: node_js
node_js:
 - "stable"

install: npm install

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - server/sequelize db:migrate
  - server/sequelize db:seed:all

script: npm test

after_success: npm run coverage

# after_success: npm run coverage