const actionTypes = {
  GET_RECIPE: 'GET_RECIPE',
  GET_RECIPES: 'GET_RECIPES',
  GET_USER_RECIPES: 'GET_USER_RECIPES',
  GET_USER_FAVOURITED_RECIPES_ID: 'GET_USER_FAVOURITED_RECIPES_ID',
  GET_FAVOURITED_RECIPES: 'GET_FAVOURITED_RECIPES',
  GET_POPULAR_RECIPES: 'GET_POPULAR_RECIPES',
  GET_RECIPE_REVIEWS: 'GET_RECIPE_REVIEWS',
  RECIPE_CATEGORIES: 'RECIPE_CATEGORIES',
  RECIPE_CATEGORY: 'RECIPE_CATEGORY',
  SEARCH_RECIPES: 'SEARCH_RECIPES',
  ADD_RECIPE: 'ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  EDIT_RECIPE: 'EDIT_RECIPE',
  TOGGLE_FAVOURITE_RECIPE: 'TOGGLE_FAVOURITE_RECIPE',
  TOGGLE_THUMBS_UP_RECIPE: 'TOGGLE_THUMBS_UP_RECIPE',
  TOGGLE_THUMBS_DOWN_RECIPE: 'TOGGLE_THUMBS_DOWN_RECIPE',
  REVIEW_RECIPE: 'REVIEW_RECIPE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_PROFILE: 'UPDATE_PROFILE'
};

export default actionTypes;
